// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ecLlZ3PUO7Q-LZjVRP823dVj2ChMPUg',
    appId: '1:1052277485580:web:fc37d1c6a497fb06b03e29',
    messagingSenderId: '1052277485580',
    projectId: 'bims-mobile-7d6d6',
    authDomain: 'bims-mobile-7d6d6.firebaseapp.com',
    storageBucket: 'bims-mobile-7d6d6.firebasestorage.app',
    measurementId: 'G-JTHPRS0HJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDakqh0K9Ty3Dit4J5x0Ly4GmCnxxBuZfs',
    appId: '1:1052277485580:android:07e998ee3d13e597b03e29',
    messagingSenderId: '1052277485580',
    projectId: 'bims-mobile-7d6d6',
    storageBucket: 'bims-mobile-7d6d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp8jmhsAHZ56_6fPhShbVLSFqsUyH_qS8',
    appId: '1:1052277485580:ios:d4525aa2439f29adb03e29',
    messagingSenderId: '1052277485580',
    projectId: 'bims-mobile-7d6d6',
    storageBucket: 'bims-mobile-7d6d6.firebasestorage.app',
    iosBundleId: 'com.example.bimsMobileGeneral',
  );
}
